import type { OxenModel } from "./oxen";

/** Live Oxen catalog id. One model covers text, keyframes, and continuation. */
export const FLUX_3_VIDEO_MODEL_ID = "flux-3-video";

/**
 * Snapshot of the public model detail used when the live schema cannot be loaded.
 * Generate still posts to the async queue; this is not a second endpoint.
 */
export const flux3VideoModel: OxenModel = {
  id: FLUX_3_VIDEO_MODEL_ID,
  display_name: "FLUX 3 Video",
  description:
    "FLUX 3 Video generates video from a text prompt, from keyframes, or by continuing an existing clip. Clips run 5 to 20 seconds at 720p or 1080p, with synchronized audio generated by default.\n\nDraft mode trades quality for a lower per-second rate and is useful for iterating before a full generation.\n",
  endpoint: "/videos/generate",
  capabilities: { input: ["text", "image", "video"], output: ["video"] },
  pricing: { method: "per_video_output_second", cost_per_second: 0.221 },
  request_schema: {
    type: "object",
    title: "Input",
    required: ["prompt"],
    basic: ["input_image", "input_video"],
    properties: {
      prompt: {
        type: "string",
        title: "Prompt",
        description: "Free-form prompt describing the video.",
      },
      input_image: {
        type: "array",
        nullable: true,
        title: "Keyframes",
        description:
          "Images that become frames of the generated video, 1 to 10 in order: one image starts the video, two start and end it, and beyond that the first starts it, the last ends it, and the rest fall evenly in between. They are frames, not references, so the prompt cannot cite them. Leave empty to generate from the prompt alone. Cannot be combined with Continue From Video.",
        items: { type: "string", format: "uri" },
      },
      input_video: {
        type: "string",
        format: "uri",
        title: "Continue From Video",
        description:
          "Clip to extend; the generated video carries on from its final frames. MP4. Cannot be combined with Keyframes. Billed at a higher per-second rate than generating from a prompt or keyframes.",
      },
      generate_audio: {
        type: "boolean",
        default: true,
        title: "Generate Audio",
        description: "Generate synchronized audio for the video.",
      },
      aspect_ratio: {
        type: "string",
        default: "auto",
        title: "Aspect Ratio",
        enum: ["auto", "21:9", "2:1", "16:9", "4:3", "1:1", "3:4", "9:16"],
      },
      resolution: {
        type: "string",
        default: "720p",
        title: "Resolution",
        enum: ["720p", "1080p"],
      },
      duration: {
        type: "integer",
        default: 5,
        minimum: 5,
        maximum: 20,
        title: "Duration",
      },
      draft: {
        type: "boolean",
        default: false,
        title: "Draft",
        description:
          "Draft mode: rapid, cost-effective exploration at a lower per-second rate. HD only.",
      },
      safety_tolerance: {
        type: "integer",
        default: 2,
        title: "Safety Tolerance",
        description: "Safety filter strictness, 0 is strictest.",
        enum: [0, 1, 2, 3, 4],
      },
    },
  },
};
